on:
  shedule: {cron: 0 */6 * * *}
  pull_request: {branches: master}
  push:
    - branches: master
    - tags: v*

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test integration with Refactr.it
    steps:
      - name: Run action
        uses: refactr/action-run-pipeline@v1
        with:
          project_id: 5e1e27f24258f8003814ce3a
          job_id: 5f031f6d9d1b5242e657443b
          variables: '{ "greeting": "GitHub Actions Test!" }'
          api_token: ${{ secrets.REFACTR_AUTH_TOKEN }}
          api_url: 'https://api.erde.refactr.it/'
